---
- name: Set localhost address for mgmt port
  set_fact:
    localhost_address: "{% if splunk.listen_on_ipv6 %}{{ '[::1]' }}{% else %}{{ '0.0.0.0' }}{% endif %}"
    win_localhost_address: "{% if splunk.listen_on_ipv6 %}{{ '[::1]' }}{% else %}{{ '127.0.0.1' }}{% endif %}"

- name: Set mgmt port
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/web.conf"
    section: settings
    option: "mgmtHostPort"
    value: "{{ localhost_address}}:{{ splunk.svc_port }}"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
  when:
    - "'svc_port' in splunk"
    - ansible_system is not match("CYGWIN*|Win32NT")
  register: set_mgmt_port

- name: Set mgmt port (Windows)
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/web.conf"
    section: settings
    option: "mgmtHostPort"
    value: "{{ win_localhost_address }}:{{ splunk.svc_port }}"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
  when:
    - "'svc_port' in splunk"
    - ansible_system is match("CYGWIN*|Win32NT")
    - splunk.svc_port | int != 8089
  register: set_mgmt_port

# Restart only when Splunk is running and when any of the above have changed
- include_tasks: ../handlers/restart_splunk.yml
  when: set_mgmt_port is changed
